{
  "hash": "5a851aba60ab45e23ffc7e8a3152c43f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Foundations 01 — Positron and the R Environment\"\nsubtitle: \"STAT/DATA 1810 · Week 1 Wednesday · SOLUTION\"\nauthor: \"Instructor key\"\nformat:\n  html:\n    toc: true\nexecute:\n  warning: false\n  message: false\n---\n\n```{=html}\n<!--\nCLO: 1.1, 1.2, 1.3, 1.4, 1.7 · 11.1 · (9 practiced)\nTiming: panes+session 12' · running code/chunks 12' · objects 16'\n        · functions/pkgs/help 20' · errors 12' · save & render 8' = 80'\nWatch the clock at the end of §2 (40' mark) — if behind, cut YT6 and YT7c.\n-->\n```\n\n**Name:** Instructor key · **Date:** \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\n\n**Labels:** **LM = Learning Moment** (instructor demonstrates, students follow). **YT = Your Turn** (students do it themselves). Say both names out loud the first time each appears — students otherwise guess.\n\n# 0 · Getting set up and what you are looking at (12 min)\n\n## Setup checklist\n\n**Teaching note:** the eight setup steps (install R → install Positron → download the `.qmd` → make `Desktop/R/{Notes,Labs}` and `Desktop/Data` → move the file into `R/Notes` → open Positron → **File → Open Folder…** on `Desktop/R` → open the file from the sidebar → fill in name and date) should be done *before* class. Budget 3 minutes at the start to rescue whoever isn't there yet; the most common failures are (a) the file is still in `Downloads`, and (b) they opened the *file* rather than the *folder*, so the Explorer sidebar is empty. The fix for both is the same: File → Open Folder… → `Desktop/R`. Make them fill in name and date — it is the first thing they type into a `.qmd`, and it is how you tell whose render is whose.\n\n## The panes (6 min)\n\n**Teaching note:** put the annotated screenshot (`images/positron_panes.png`) on the projector and have students physically point at each numbered pane; the checklist is the activity. Use Positron's own names consistently — **Editor**, **Console**, **Variables**, **Plots**, **Explorer** — because that is what students see on screen. Two traps: the **CONSOLE** tab and the **TERMINAL** tab sit side by side at the bottom and students click the wrong one (the Terminal shows a `%` prompt, not `>`); and Variables/Plots live inside the **SESSION** panel on the right, so if a student has closed it, the right side looks blank. Terminal/Viewer/Connections get one sentence each — resist the tour becoming the lesson.\n\n**YT1:** Variables. **YT2:** the Editor (this `.qmd`).\n\n## The Session (6 min)\n\n**Teaching note — getting to the Session tab.** Point at the top-right interpreter label (`R 4.x.x`, arrow 6 on the screenshot). Click it once so they see the menu: the running session, Restart, Shutdown, and any other interpreters. Press Escape. Then point at the **SESSION** panel beneath it and say: \"that label is the session; this panel is what the session remembers.\" Say the three facts (memory / restartable / replaceable) and move on. The payoff comes in §4 LM11 when they restart for real. Show that Variables is empty *now* — that \"before\" picture makes the restart in §4 land.\n\n**Q1 model answer:** the Console runs code once and forgets it; the Editor holds code you keep, so you can re-run everything tomorrow.\n\n# 1 · Running code and code chunks (12 min)\n\n**LM1:** the up-arrow trick saves students dozens of retypes this term — worth the 20 seconds.\n\n**LM2 teaching note — anatomy of a chunk.** Put the cursor on the ```` ```{r} ```` line and name its parts out loud: fence, `{r}` = \"this is R\", fence. Then click the play button so they see output land **both** under the chunk and in the Console. The sentence to leave them with: *\"a chunk is a saved bundle of Console lines.\"* Students create their own chunks starting Monday (Foundations 02) — today they only run and edit ours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM2\n2 + 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\n3 * 7\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21\n```\n\n\n:::\n\n```{.r .cell-code}\n10 / 4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.5\n```\n\n\n:::\n:::\n\n\n**LM3:** one sentence on `#|` options is enough. They'll write `#| label:` and `#| eval: false` themselves in ETV cycles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT3\n5 - 4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n100 / 8\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.5\n```\n\n\n:::\n\n```{.r .cell-code}\n2^10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1024\n```\n\n\n:::\n:::\n\n\n**Expected:** 1 · 12.5 · 1024. **Q2:** both.\n\n# 2 · Objects and assignment (16 min)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM4\ncups <- 3\ncups\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM5 — prediction: 13.5\nprice <- 4.50\ntotal <- cups * price\ntotal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM6\ncups <- 10\ntotal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.5\n```\n\n\n:::\n:::\n\n\n**Q4 model answer:** `total` was computed *at the moment* the `<-` line ran, using `cups = 3`. Changing `cups` later doesn't re-run old lines — R objects store values, not formulas. **This is the single most important idea of the day**; spend the full minutes here. (Spreadsheet contrast lands well: Excel cells recompute; R objects don't.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4 — any sleep value; e.g.\nhours   <- 7\nminutes <- hours * 60\nminutes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 420\n```\n\n\n:::\n\n```{.r .cell-code}\nhours   <- 8\nminutes            # still 420 — same lesson as Q4, now self-discovered\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 420\n```\n\n\n:::\n:::\n\n\n**YT4 (d):** `minutes` does not change. This is Q4 again, but the student built it, so it sticks. Have two students say their prediction and result aloud. Then point at Variables: `cups`, `price`, `total`, `hours`, `minutes` — five objects, all session memory.\n\n# 3 · Functions, packages, help (20 min)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM7\nmean(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.09062\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32\n```\n\n\n:::\n:::\n\n\n**Expected:** 20.09062 · 32.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT5\nmax(mtcars$hp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 335\n```\n\n\n:::\n\n```{.r .cell-code}\nmin(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.4\n```\n\n\n:::\n\n```{.r .cell-code}\nncol(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11\n```\n\n\n:::\n\n```{.r .cell-code}\nround(mean(mtcars$mpg), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.1\n```\n\n\n:::\n:::\n\n\n**Expected:** 335 (the Maserati Bora) · 10.4 · 11 · 20.1. Part (d) is the first *nested* call — say \"inside out\" once; don't dwell.\n\n**Q5 model answer:** `na.rm = TRUE` tells `mean()` to remove `NA` values before computing; the default `FALSE` returns `NA` if any value is missing. (Plant the flag: this argument returns in Foundations 03 and every ETV cycle.)\n\n**YT6:** `digits`, default `0`. The purpose is reading a Usage line, not the fact itself.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n**Q6:** install runs **once** per computer; library runs **once every session**. Analogy that sticks: install = buying the drill; library = taking it out of the garage.\n\n# 4 · When things break (12 min)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeen(mtcars$mpg)\n#> Error in meen(mtcars$mpg) : could not find function \"meen\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM10 fixed\nmean(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.09062\n```\n\n\n:::\n:::\n\n\n**Q7 model answer:** \"could not find function\" means the *name* doesn't exist — a typo, or a package not loaded. **Teaching note:** name the two most common error families now: `could not find function` (typo/library) and `object not found` (name typo / never created). Students who can *classify* an error stop fearing errors.\n\n**YT7 answers:**\n\n-   **7a** `mtcars$mgp` → returns `NULL`, and `mean` warns \"argument is not numeric or logical: returning NA\". Family: **column-name typo** (`$` on a missing column gives `NULL`, not an error — worth saying, since it's the sneakiest of the three). Fix: `mpg`.\n-   **7b** `Mtcars` → `Error: object 'Mtcars' not found`. Family: **object not found** (R is case-sensitive). Fix: `mtcars`.\n-   **7c** missing `)` → the Console shows a `+` prompt waiting for more; in a chunk, \"unexpected end of input\". Family: **unbalanced parentheses**. Fix: add `)`. Show them **Escape** in the Console to get out of a `+` prompt.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.09062\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.09062\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.09062\n```\n\n\n:::\n:::\n\n\n**LM11 — restart for real.** Everyone restarts. Variables empties. Then Q8: `cups` gone · code still here · re-running §2 takes \\~10 seconds. That 10-second recovery *is* the argument for putting code in the file.\n\n# 5 · Save & render (8 min)\n\n**Exit model answer:** `cups` lives in Variables (gone after restart); this `.qmd` lives in the Editor (survives). The code that *recreates* `cups` survives — which is the entire argument for reproducible documents, made on day one without ever saying \"CLO 9.\"",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}