{
  "hash": "15378a64dd17850b8ec4192baa12a357",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ETV Cycle 02 — Kobe Bryant's First Five Seasons\"\nsubtitle: \"STAT/DATA 1810 · In-class activity · SOLUTION\"\nauthor: \"Instructor key\"\nformat:\n  html:\n    toc: true\nexecute:\n  warning: false\n  message: false\n---\n\n<!--\nCLO ALIGNMENT (assessed via lab receipt + drills)\n  CLO 2.2 read_excel (sheets) · CLO 3.1 filter/select/mutate/group_by/summarize\n  CLO 4.1 geom_point · CLO 4.5 claim · CLO 12.2 measurement · 12.6 transparency\nTiming: 0 Ethics 8' · E 15' · T 27' · V 20' · Answer 10' = 80'\n-->\n\n# 0 · Context & ethics (8 min)\n\nOur data are Kobe Bryant's game-level records compiled from Basketball-Reference.\n\n**Talking points.** Check terms of service and `robots.txt` before scraping;\nuse the prepared workbook and its `variable_names` sheet for provenance. Raw\npoint totals also depend on games played and minutes, so a rate makes the\ncomparison more defensible.\n\n# 1 · The central question\n\n> **How did Kobe Bryant's scoring performance change across his first five\n> NBA seasons?** Measure: points per minute.\n\n# 2 · E — Extraction (15 min)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\n# LM1a: sheets\nexcel_sheets(\"Data/nba_goats.xlsx\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"KB\"             \"LJ\"             \"MJ\"             \"variable_names\"\n[5] \"divisions\"     \n```\n\n\n:::\n:::\n\n\n**Expected:** `KB`, `LJ`, `MJ`, `variable_names`, and `divisions`. The `KB` sheet\ncontains Kobe's game-level records; the metadata sheet documents the fields.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM1b: read Kobe's game-level data\nnba_df <- read_excel(\"Data/nba_goats.xlsx\", sheet = \"KB\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM2: inspect\n glimpse(nba_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,156\nColumns: 38\n$ Name          <chr> \"KB\", \"KB\", \"KB\", \"KB\", \"KB\", \"KB\", \"KB\", \"KB\", \"KB\", \"K…\n$ Season        <chr> \"season_1\", \"season_1\", \"season_1\", \"season_1\", \"season_…\n$ Game_Location <chr> \"Home\", \"Home\", \"Away\", \"Away\", \"Away\", \"Home\", \"Away\", …\n$ Game_Outcome  <chr> \"W\", \"W\", \"W\", \"L\", \"L\", \"W\", \"W\", \"L\", \"W\", \"W\", \"W\", \"…\n$ Point_Margin  <dbl> 14, 6, 6, -10, -1, 7, 11, -12, 7, 14, 3, -16, 10, -5, 12…\n$ Rk            <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…\n$ G             <dbl> NA, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, NA, NA, 12, 13, 1…\n$ Date          <dttm> 1996-11-01, 1996-11-03, 1996-11-05, 1996-11-06, 1996-11…\n$ Age           <chr> \"18-070\", \"18-072\", \"18-074\", \"18-075\", \"18-077\", \"18-07…\n$ Tm            <chr> \"LAL\", \"LAL\", \"LAL\", \"LAL\", \"LAL\", \"LAL\", \"LAL\", \"LAL\", …\n$ Opp           <chr> \"PHO\", \"MIN\", \"NYK\", \"CHH\", \"TOR\", \"ATL\", \"HOU\", \"SAS\", …\n$ GS            <dbl> NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, NA, 0, 0, 0, 0,…\n$ MP            <dbl> NA, 6.22, 3.16, 6.49, 17.15, 8.25, 5.03, 6.06, 7.01, 14.…\n$ FG            <dbl> NA, 0, 0, 2, 3, 0, 1, 2, 1, 5, 0, 4, NA, NA, 4, 1, 0, 1,…\n$ FGA           <dbl> NA, 1, 1, 3, 8, 3, 2, 2, 4, 8, 2, 5, NA, NA, 10, 7, 1, 2…\n$ FG_Percent    <dbl> NA, 0.000, 0.000, 0.667, 0.375, 0.000, 0.500, 1.000, 0.2…\n$ `3P`          <dbl> NA, 0, 0, 1, 2, 0, 0, 1, 0, 4, 0, 3, NA, NA, 2, 0, 0, 0,…\n$ `3PA`         <dbl> NA, 0, 0, 2, 3, 0, 1, 1, 2, 6, 1, 3, NA, NA, 5, 3, 0, 0,…\n$ `3P_Percent`  <dbl> NA, NA, NA, 0.500, 0.667, NA, 0.000, 1.000, 0.000, 0.667…\n$ FT            <dbl> NA, 0, 1, 0, 2, 2, 0, 1, 2, 2, 3, 0, NA, NA, 2, 0, 1, 0,…\n$ FTA           <dbl> NA, 0, 2, 0, 4, 2, 0, 1, 3, 2, 4, 0, NA, NA, 2, 0, 2, 0,…\n$ FT_Percent    <dbl> NA, NA, 0.500, NA, 0.500, 1.000, NA, 1.000, 0.667, 1.000…\n$ ORB           <dbl> NA, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, NA, NA, 0, 1, 1, 0,…\n$ DRB           <dbl> NA, 1, 0, 0, 3, 2, 1, 0, 0, 0, 2, 1, NA, NA, 1, 3, 0, 1,…\n$ TRB           <dbl> NA, 1, 0, 0, 3, 3, 1, 0, 0, 2, 2, 1, NA, NA, 1, 4, 1, 1,…\n$ AST           <dbl> NA, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, NA, NA, 1, 1, 0, 0,…\n$ STL           <dbl> NA, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, NA, NA, 0, 0, 0, 0,…\n$ BLK           <dbl> NA, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, NA, NA, 0, 1, 1, 0,…\n$ TOV           <dbl> NA, 1, 1, 3, 0, 0, 2, 0, 1, 4, 1, 2, NA, NA, 3, 2, 0, 1,…\n$ PF            <dbl> NA, 1, 0, 0, 3, 0, 0, 2, 4, 2, 2, 1, NA, NA, 1, 3, 1, 0,…\n$ PTS           <dbl> NA, 0, 1, 5, 10, 2, 2, 6, 4, 16, 3, 11, NA, NA, 12, 2, 1…\n$ GmSc          <dbl> NA, -1.1, -1.1, 0.7, 5.2, 1.9, -0.7, 5.6, -1.4, 10.4, 0.…\n$ number_game   <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…\n$ DD            <dbl> NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, NA, 0, 0, 0, 0,…\n$ TD            <dbl> NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, NA, 0, 0, 0, 0,…\n$ Age_Years     <dbl> 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, …\n$ Age_Days      <dbl> 70, 72, 74, 75, 77, 79, 81, 82, 84, 86, 88, 89, 91, 93, …\n$ Last_Name     <chr> \"Bryant\", \"Bryant\", \"Bryant\", \"Bryant\", \"Bryant\", \"Bryan…\n```\n\n\n:::\n\n```{.r .cell-code}\n nba_df |> count(Season)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Season\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"season_1\",\"2\":\"82\"},{\"1\":\"season_10\",\"2\":\"82\"},{\"1\":\"season_11\",\"2\":\"82\"},{\"1\":\"season_12\",\"2\":\"82\"},{\"1\":\"season_13\",\"2\":\"82\"},{\"1\":\"season_14\",\"2\":\"82\"},{\"1\":\"season_15\",\"2\":\"82\"},{\"1\":\"season_2\",\"2\":\"82\"},{\"1\":\"season_3\",\"2\":\"50\"},{\"1\":\"season_4\",\"2\":\"67\"},{\"1\":\"season_5\",\"2\":\"82\"},{\"1\":\"season_6\",\"2\":\"82\"},{\"1\":\"season_7\",\"2\":\"82\"},{\"1\":\"season_8\",\"2\":\"69\"},{\"1\":\"season_9\",\"2\":\"68\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Expected:** 1,156 rows and 38 variables. The performance fields are `MP`\n(minutes played) and `PTS` (points). The season counts include `season_1` with\n82 rows but only 71 complete game records, because some rows have no box-score\nvalues; that is why LM3 filters for non-missing performance values.\n\n# 3 · T — Transformation (27 min)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM3: first five seasons with complete game records\nkobe_df <- nba_df |>\n  filter(Season %in% paste0(\"season_\", 1:5),\n         !is.na(MP), !is.na(PTS))\n\nnrow(kobe_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 334\n```\n\n\n:::\n:::\n\n\n**Expected:** 334 complete game rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM4: select what matters and create the rate\nkobe_df <- kobe_df |>\n  select(Season, MP, PTS) |>\n  mutate(season_number = readr::parse_number(Season),\n         ppm = PTS / MP)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM5: summarize and arrange by season_number\nkobe_table_df <- kobe_df |>\n  group_by(Season, season_number) |>\n  summarize(games = n(),\n            points = sum(PTS),\n            minutes = sum(MP),\n            ppm = points / minutes,\n            .groups = \"drop\") |>\n  arrange(season_number) |>\n  mutate(ppm = round(ppm, 3))\n\nkobe_table_df\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Season\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"season_number\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"games\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"points\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"minutes\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ppm\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"season_1\",\"2\":\"1\",\"3\":\"71\",\"4\":\"539\",\"5\":\"1087.70\",\"6\":\"0.496\"},{\"1\":\"season_2\",\"2\":\"2\",\"3\":\"79\",\"4\":\"1220\",\"5\":\"2042.93\",\"6\":\"0.597\"},{\"1\":\"season_3\",\"2\":\"3\",\"3\":\"50\",\"4\":\"996\",\"5\":\"1882.57\",\"6\":\"0.529\"},{\"1\":\"season_4\",\"2\":\"4\",\"3\":\"66\",\"4\":\"1485\",\"5\":\"2509.82\",\"6\":\"0.592\"},{\"1\":\"season_5\",\"2\":\"5\",\"3\":\"68\",\"4\":\"1938\",\"5\":\"2778.23\",\"6\":\"0.698\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Expected table:**\n\n| Season | games | points | minutes | ppm |\n|---|---:|---:|---:|---:|\n| season_1 | 71 | 539 | 1087.70 | 0.496 |\n| season_2 | 79 | 1220 | 2042.93 | 0.597 |\n| season_3 | 50 | 996 | 1882.57 | 0.529 |\n| season_4 | 66 | 1485 | 2509.82 | 0.592 |\n| season_5 | 68 | 1938 | 2778.23 | 0.697 |\n\n# 4 · V — Visualization (20 min)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM6: time-ordered point plot\nggplot(kobe_table_df, aes(x = season_number, y = ppm)) +\n  geom_point(size = 3, color = \"#12263A\") +\n  scale_x_continuous(breaks = 1:5) +\n  labs(x = \"Season number\", y = \"Points per minute\",\n       title = \"Kobe's scoring rate climbed across his first five seasons\")\n```\n\n::: {.cell-output-display}\n![](etv02_nba_solution_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n*(Optional companion plot — the measurement beat made visible:)*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(kobe_table_df, aes(x = season_number, y = points)) +\n  geom_point(size = 3, color = \"#A63D2F\") +\n  scale_x_continuous(breaks = 1:5) +\n  labs(x = \"Season number\", y = \"Total points\",\n       title = \"Raw totals dip in season 3, the 50-game lockout season\")\n```\n\n::: {.cell-output-display}\n![](etv02_nba_solution_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Teaching note:** the two plots disagree about season 3. Totals decline\nbecause the season had only 50 games; the rate remains near the surrounding\nseasons. That disagreement is the measurement lesson.\n\n# 5 · Interpretation & final answer (10 min)\n\n**Model answer:** *\"Kobe's scoring rate rose from about 0.496 points per minute\nin season 1 to about 0.697 in season 5, an increase of roughly 41%. The climb\nwas not perfectly steady: season 3 has fewer total points because the lockout\nlimited the schedule to 50 games, while its per-minute rate remained near 0.53.\nA raw total would have misled us there.\"*\n\nRequired elements: **direction, magnitude, and the lockout caveat** —\ndirection/size/caveat is the CLO 4.5 trio for this cycle.\n",
    "supporting": [
      "etv02_nba_solution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}