#!/usr/bin/env python3
"""Explicitly publish (or unpublish) a check-in document to the course website.

Nothing in R/check_in/generated/ ever reaches the website. This script is the
ONLY path: it copies one approved .docx into R/check_in/public/, flips the
matching *_published flag in the source JSON, records it in public/manifest.json,
and regenerates R/check_in/checkins.qmd (the page Quarto renders).

  python R/check_in/scripts/publish_checkin.py --week 1 --type self   --version blank
  python R/check_in/scripts/publish_checkin.py --week 1 --type self   --version solution
  python R/check_in/scripts/publish_checkin.py --week 1 --type collab --version blank --unpublish
  python R/check_in/scripts/publish_checkin.py --status
  python R/check_in/scripts/publish_checkin.py --check      # audit docs/ for leaks

Rubrics can never be published. Then:  quarto render  →  git commit  →  git push.
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]               # R/check_in
REPO = ROOT.parents[1]
SOURCE_DIRS = {"self": ROOT / "check_in_self", "collab": ROOT / "check_in_collab"}
GENERATED = ROOT / "generated"
PUBLIC = ROOT / "public"
MANIFEST = PUBLIC / "manifest.json"
PAGE = ROOT / "checkins.qmd"
DOCS = REPO / "docs"
PUBLISHABLE = ("blank", "solution")
LABELS = {"self": "Self Check-In", "collab": "Collaborative Check-In"}


def load_manifest():
    if MANIFEST.exists():
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    return {"published": []}


def save_manifest(m):
    PUBLIC.mkdir(parents=True, exist_ok=True)
    m["published"] = sorted(m["published"], key=lambda e: (e["week"], e["type"], e["version"]))
    MANIFEST.write_text(json.dumps(m, indent=2) + "\n", encoding="utf-8")


def set_flag(week, ctype, version, value):
    src = SOURCE_DIRS[ctype] / f"week_{week:02d}.json"
    if not src.exists():
        sys.exit(f"Source JSON not found: {src}")
    quiz = json.loads(src.read_text(encoding="utf-8"))
    quiz[f"{version}_published"] = value
    src.write_text(json.dumps(quiz, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return quiz


def write_page(m):
    lines = [
        "---",
        'title: "Check-Ins"',
        'subtitle: "Released check-in quizzes — blank versions and, when released, solutions"',
        "toc: false",
        "---",
        "",
        "<!-- GENERATED by R/check_in/scripts/publish_checkin.py — do not edit by hand. -->",
        "",
        "::: {.callout-note title=\"How this page works\"}",
        "- Only check-ins the instructor has **explicitly released** appear here",
        "- Solutions are released separately from the blank versions, and only after the quiz has been given",
        ":::",
        "",
    ]
    pub = m["published"]
    if not pub:
        lines += ["*No check-ins have been released yet.*", ""]
    else:
        weeks = sorted({e["week"] for e in pub})
        for wk in weeks:
            lines += [f"## Week {wk}", "", "| Check-in | Blank | Solution |", "|:--|:--:|:--:|"]
            for ct in ("self", "collab"):
                entries = {e["version"]: e for e in pub if e["week"] == wk and e["type"] == ct}
                if not entries:
                    continue
                cell = lambda v: (f"[{v.title()}](public/{entries[v]['file']}){{download=\"{Path(entries[v]['file']).name}\" target=\"_self\"}}"
                                  if v in entries else "—")
                lines.append(f"| {LABELS[ct]} | {cell('blank')} | {cell('solution')} |")
            lines.append("")
    PAGE.write_text("\n".join(lines), encoding="utf-8")


def publish(week, ctype, version):
    src = GENERATED / f"week_{week:02d}" / ctype / f"week_{week:02d}_{ctype}_{version}.docx"
    if not src.exists():
        sys.exit(f"Not built yet: {src.relative_to(REPO)}\n"
                 f"Run:  python R/check_in/scripts/build_checkins.py --week {week} --type {ctype}")
    dest_dir = PUBLIC / f"week_{week:02d}"
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / src.name
    shutil.copy2(src, dest)
    m = load_manifest()
    m["published"] = [e for e in m["published"] if not (e["week"] == week and e["type"] == ctype and e["version"] == version)]
    m["published"].append({"week": week, "type": ctype, "version": version, "file": f"week_{week:02d}/{src.name}"})
    save_manifest(m)
    set_flag(week, ctype, version, True)
    write_page(m)
    print(f"PUBLISHED  {dest.relative_to(REPO)}")
    print("Next:  quarto render   then   git add -A && git commit && git push")


def unpublish(week, ctype, version):
    dest = PUBLIC / f"week_{week:02d}" / f"week_{week:02d}_{ctype}_{version}.docx"
    m = load_manifest()
    m["published"] = [e for e in m["published"] if not (e["week"] == week and e["type"] == ctype and e["version"] == version)]
    if dest.exists():
        dest.unlink()
    if dest.parent.exists() and not any(dest.parent.iterdir()):
        dest.parent.rmdir()
    save_manifest(m)
    set_flag(week, ctype, version, False)
    write_page(m)
    # also remove from the rendered site immediately so a re-render isn't the only barrier
    rendered = DOCS / "R" / "check_in" / "public" / f"week_{week:02d}" / dest.name
    if rendered.exists():
        rendered.unlink()
    print(f"UNPUBLISHED  {dest.relative_to(REPO)}")
    print("Next:  quarto render   then   git add -A && git commit && git push  (removes it from GitHub Pages)")


def status():
    m = load_manifest()
    if not m["published"]:
        print("Nothing published.")
    for e in m["published"]:
        print(f"  week {e['week']:>2}  {e['type']:<6}  {e['version']:<8}  public/{e['file']}")


def check():
    """Audit: every .docx under docs/ must be listed in the manifest; nothing else leaks."""
    allowed = {f"R/check_in/public/{e['file']}" for e in load_manifest()["published"]}
    leaks = []
    for p in DOCS.rglob("*.docx"):
        rel = str(p.relative_to(DOCS))
        if rel not in allowed:
            leaks.append(rel)
    for p in DOCS.rglob("*"):
        if "check_in" in p.parts and p.is_file() and ("generated" in p.parts or p.suffix == ".json" and p.name != "manifest.json"):
            leaks.append(str(p.relative_to(DOCS)))
    if leaks:
        print("LEAK — unpublished assessment files found in docs/:")
        for l in leaks:
            print("   ", l)
        sys.exit(1)
    print(f"OK — docs/ contains only the {len(allowed)} published check-in file(s).")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--week", type=int)
    ap.add_argument("--type", choices=tuple(SOURCE_DIRS))
    ap.add_argument("--version", choices=("blank", "solution", "rubric"))
    ap.add_argument("--unpublish", action="store_true")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if a.status:
        return status()
    if a.check:
        return check()
    if a.week is None or not a.type or not a.version:
        ap.error("--week, --type and --version are all required (or use --status / --check)")
    if a.version not in PUBLISHABLE:
        sys.exit("Rubrics are instructor-only and can never be published.")
    (unpublish if a.unpublish else publish)(a.week, a.type, a.version)


if __name__ == "__main__":
    main()
