{
  "hash": "718745b74bb4263989787d3973cb8a14",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Foundations 03 — Inspecting and Accessing Data\"\nsubtitle: \"STAT/DATA 1810 · Week 2 Wednesday · SOLUTION\"\nauthor: \"Instructor key\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-location: right-body\n    toc-title: \"Contents\"\nexecute:\n  warning: false\n  message: false\n---\n\n<!--\nCLO ALIGNMENT\n  CLO 1 (1.6 containers in use · 1.12 storage magnitudes, object.size/file.size)\n  CLO 1 accessing: $, [ ], [[ ]]  (kept light — the tidyverse verbs take over Monday)\n  CLO 7 (7.6 is.na in practice)\n  CLO 9 practiced: you insert your own chunks (➕)\nTime: 80 min. Datasets: airquality, iris, mtcars (built in).\nTiming: job 2' · inspecting 20' · accessing 18' · the pipe 15' · when things break 5'\n        · storage 11' · ETV preview 5' · exit 4' = 80'\nCheckpoint: §3 (the pipe) starts by 40'. If behind, cut YT3(c) and YT5.\nCarries the Fnd 01 conventions: Name/Date line, LM/YT legend, 👀 Variables\nchecks, a 'when things break' section, restart-then-render close.\nPackages: tibble only (glimpse()). The pipe |> is base R — no package needed.\nEnds with a 5-minute live preview of a full ETV cycle — where all of this is going.\nLM = learning moment. YT = your turn. Times in headers are the section budget.\n-->\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tibble)   # for glimpse(). The pipe |> is built into R — nothing to load.\n```\n:::\n\n\n> 👀 **Variables check.** Still empty after `library()`. And `airquality`,\n> which we use all class, will *never* appear there — it ships inside a\n> package. Variables shows only what *this session* created.\n\n**Name:** Instructor key · **Date:** \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\n\n> Before anything else, type your name and today's date on the line above (and put your name in the `author:` line at the very top of this file).\n\n**How to read this document.** Two labels show up over and over:\n\n- **LM = Learning Moment.** I demonstrate; you follow along and run the code.\n- **YT = Your Turn.** You do it yourself — fill the blank or the empty chunk.\n- **👀 Variables check.** Glance at the **Variables** pane (right side, under\n  SESSION) and answer the question. It is your session's memory made visible.\n\n::: {.callout-warning title=\"Timing & labels\"}\n- **Budget:** job 2′ · inspecting 20′ · accessing 18′ · the pipe 15′ · when things break 5′ · storage 11′ · ETV preview 5′ · exit 4′ = **80′**\n- **Checkpoint:** §3 (the pipe) starts by **40′** — if behind, cut YT3(c) and YT5\n- [LM]{.lm} **Learning Moment** — instructor demonstrates, students follow\n- [YT]{.yt} **Your Turn** — students do it themselves\n- 👀 **Variables check** — the Fnd 01 / Lab 01 habit; keep it alive: every 👀 is a 20-second look at the pane, not a discussion\n- Say the LM/YT names out loud the first time each appears — students otherwise guess\n- `$` / `[ ]` are deliberately lighter than before: enough to read code and grab a column, not a drill. The pipe and \"how big is data\" got the time instead\n- The ETV preview closes foundations: run a Cycle-0-style coffee import → plot live, narrating nothing but the three stage names — Monday they drive C1\n:::\n\n# 0 · Today's job [2 min]{.timing}\n\nYou get handed a dataset. Before any analysis, you must answer three\nquestions: **What is this? How big is it? What's inside?** Today is those\nthree questions, as functions — then how to *reach in and take a piece* —\nand then the one symbol that will carry every line of code you write for\nthe rest of the quarter.\n\n{{< vspace 1.5rem >}}\n\n# 1 · Inspecting data [20 min]{.timing}\n\nWe'll interrogate `airquality` — 1973 New York air measurements, built in.\n\n**LM1 — the first look (5 min).** Run each; note what question each answers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM1: five inspection functions\nhead(airquality)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Ozone\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Solar.R\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Wind\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Temp\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Month\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Day\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"41\",\"2\":\"190\",\"3\":\"7.4\",\"4\":\"67\",\"5\":\"5\",\"6\":\"1\",\"_rn_\":\"1\"},{\"1\":\"36\",\"2\":\"118\",\"3\":\"8.0\",\"4\":\"72\",\"5\":\"5\",\"6\":\"2\",\"_rn_\":\"2\"},{\"1\":\"12\",\"2\":\"149\",\"3\":\"12.6\",\"4\":\"74\",\"5\":\"5\",\"6\":\"3\",\"_rn_\":\"3\"},{\"1\":\"18\",\"2\":\"313\",\"3\":\"11.5\",\"4\":\"62\",\"5\":\"5\",\"6\":\"4\",\"_rn_\":\"4\"},{\"1\":\"NA\",\"2\":\"NA\",\"3\":\"14.3\",\"4\":\"56\",\"5\":\"5\",\"6\":\"5\",\"_rn_\":\"5\"},{\"1\":\"28\",\"2\":\"NA\",\"3\":\"14.9\",\"4\":\"66\",\"5\":\"5\",\"6\":\"6\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ntail(airquality)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Ozone\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Solar.R\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Wind\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Temp\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Month\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Day\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"14\",\"2\":\"20\",\"3\":\"16.6\",\"4\":\"63\",\"5\":\"9\",\"6\":\"25\",\"_rn_\":\"148\"},{\"1\":\"30\",\"2\":\"193\",\"3\":\"6.9\",\"4\":\"70\",\"5\":\"9\",\"6\":\"26\",\"_rn_\":\"149\"},{\"1\":\"NA\",\"2\":\"145\",\"3\":\"13.2\",\"4\":\"77\",\"5\":\"9\",\"6\":\"27\",\"_rn_\":\"150\"},{\"1\":\"14\",\"2\":\"191\",\"3\":\"14.3\",\"4\":\"75\",\"5\":\"9\",\"6\":\"28\",\"_rn_\":\"151\"},{\"1\":\"18\",\"2\":\"131\",\"3\":\"8.0\",\"4\":\"76\",\"5\":\"9\",\"6\":\"29\",\"_rn_\":\"152\"},{\"1\":\"20\",\"2\":\"223\",\"3\":\"11.5\",\"4\":\"68\",\"5\":\"9\",\"6\":\"30\",\"_rn_\":\"153\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ndim(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 153   6\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 153\n```\n\n\n:::\n\n```{.r .cell-code}\nncol(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\n> *Q1. Rows: 153 · Columns: 6 · What is one OBSERVATION here (what does\n> one row represent)?*\n>\n> *Your answer:* One row is **one day** of air measurements in New York\n> (May–September 1973): that day's Ozone, Solar.R, Wind, Temp, Month, Day.\n\n::: {.callout-tip title=\"Q1 answer\"}\n- [Q1]{.q} **153 rows × 6 columns**\n- One row = **one day** of measurements (May–Sep 1973)\n- The observation question matters more than the numbers — every dataset this term starts with \"what is a row?\"\n:::\n\n**LM2 — names and structure (4 min).**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM2\nnames(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Ozone\"   \"Solar.R\" \"Wind\"    \"Temp\"    \"Month\"   \"Day\"    \n```\n\n\n:::\n\n```{.r .cell-code}\nstr(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t153 obs. of  6 variables:\n $ Ozone  : int  41 36 12 18 NA 28 23 19 8 NA ...\n $ Solar.R: int  190 118 149 313 NA NA 299 99 19 194 ...\n $ Wind   : num  7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...\n $ Temp   : int  67 72 74 62 56 66 65 59 61 69 ...\n $ Month  : int  5 5 5 5 5 5 5 5 5 5 ...\n $ Day    : int  1 2 3 4 5 6 7 8 9 10 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 153\nColumns: 6\n$ Ozone   <int> 41, 36, 12, 18, NA, 28, 23, 19, 8, NA, 7, 16, 11, 14, 18, 14, …\n$ Solar.R <int> 190, 118, 149, 313, NA, NA, 299, 99, 19, 194, NA, 256, 290, 27…\n$ Wind    <dbl> 7.4, 8.0, 12.6, 11.5, 14.3, 14.9, 8.6, 13.8, 20.1, 8.6, 6.9, 9…\n$ Temp    <int> 67, 72, 74, 62, 56, 66, 65, 59, 61, 69, 74, 69, 66, 68, 58, 64…\n$ Month   <int> 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,…\n$ Day     <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…\n```\n\n\n:::\n:::\n\n\n> *Q2. `str()` and `glimpse()` answer the same question. Which is easier to\n> read, and what do the `<int>` / `int` tags tell you?*\n>\n> *Your answer:* `glimpse()` — one line per variable, and it fits any window\n> width. The `int` / `<int>` tags are the **data types from Monday**: every\n> column here is stored as integers (a `dbl` would mean doubles/decimals) —\n> all quantitative, even though Month is really a category.\n\n::: {.callout-tip title=\"Q2 model answer\"}\n- [Q2]{.q} `glimpse()` is easier — one line per variable, fits any width\n- The tags are the **types from Monday**: `int` integers, `dbl` doubles, `chr` character, `fct` factor\n- Point made: Monday's vocabulary is now reading equipment. Ask which *family* each column is — Month is stored quantitative but *means* categorical (Monday's item E)\n:::\n\n**LM3 — the numeric overview (3 min).**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM3\nsummary(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Ozone           Solar.R           Wind             Temp      \n Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  \n 1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  \n Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  \n Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  \n 3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  \n Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  \n NA's   :37       NA's   :7                                       \n     Month            Day      \n Min.   :5.000   Min.   : 1.0  \n 1st Qu.:6.000   1st Qu.: 8.0  \n Median :7.000   Median :16.0  \n Mean   :6.993   Mean   :15.8  \n 3rd Qu.:8.000   3rd Qu.:23.0  \n Max.   :9.000   Max.   :31.0  \n                               \n```\n\n\n:::\n:::\n\n\n> *Q3. Which TWO variables contain missing values, and how many each?\n> (summary() tells you directly.)*\n>\n> *Your answer:* **Ozone (37 NA)** and **Solar.R (7 NA)** — `summary()`\n> prints an `NA's` line under each column that has them.\n\n::: {.callout-tip title=\"Q3 answer\"}\n- [Q3]{.q} **Ozone (37 NA)** and **Solar.R (7 NA)**\n- `summary()` prints the NA counts in-column — students should find them without help\n:::\n\n*(`View(airquality)` opens a spreadsheet view — try it in the Console; it\ndoesn't belong in a rendered document.)*\n\n> *YT1 (8 min). ➕ Insert a chunk and inspect a dataset you have NOT seen:\n> `mtcars`. Use whichever of the functions above you need to answer:*\n> *(a) how many rows and columns?*\n> *(b) what is one observation (one row)? Hint: run `head()` and look at the\n> row labels on the left.*\n> *(c) which columns are NOT numeric — or are they all numeric?*\n> *(d) any missing values? How do you know?*\n> *(e) what is the median `mpg`?*\n\n<!-- ➕ insert a chunk here -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT1 — mtcars, unseen\ndim(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32 11\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(mtcars)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"mpg\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cyl\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"disp\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"hp\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"drat\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"wt\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"qsec\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"vs\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"am\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gear\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carb\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"21.0\",\"2\":\"6\",\"3\":\"160\",\"4\":\"110\",\"5\":\"3.90\",\"6\":\"2.620\",\"7\":\"16.46\",\"8\":\"0\",\"9\":\"1\",\"10\":\"4\",\"11\":\"4\",\"_rn_\":\"Mazda RX4\"},{\"1\":\"21.0\",\"2\":\"6\",\"3\":\"160\",\"4\":\"110\",\"5\":\"3.90\",\"6\":\"2.875\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"1\",\"10\":\"4\",\"11\":\"4\",\"_rn_\":\"Mazda RX4 Wag\"},{\"1\":\"22.8\",\"2\":\"4\",\"3\":\"108\",\"4\":\"93\",\"5\":\"3.85\",\"6\":\"2.320\",\"7\":\"18.61\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Datsun 710\"},{\"1\":\"21.4\",\"2\":\"6\",\"3\":\"258\",\"4\":\"110\",\"5\":\"3.08\",\"6\":\"3.215\",\"7\":\"19.44\",\"8\":\"1\",\"9\":\"0\",\"10\":\"3\",\"11\":\"1\",\"_rn_\":\"Hornet 4 Drive\"},{\"1\":\"18.7\",\"2\":\"8\",\"3\":\"360\",\"4\":\"175\",\"5\":\"3.15\",\"6\":\"3.440\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"2\",\"_rn_\":\"Hornet Sportabout\"},{\"1\":\"18.1\",\"2\":\"6\",\"3\":\"225\",\"4\":\"105\",\"5\":\"2.76\",\"6\":\"3.460\",\"7\":\"20.22\",\"8\":\"1\",\"9\":\"0\",\"10\":\"3\",\"11\":\"1\",\"_rn_\":\"Valiant\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nglimpse(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 32\nColumns: 11\n$ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8,…\n$ cyl  <dbl> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8,…\n$ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 140.8, 16…\n$ hp   <dbl> 110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, 180, 180…\n$ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.92, 3.92,…\n$ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3.150, 3.…\n$ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 22.90, 18…\n$ vs   <dbl> 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,…\n$ am   <dbl> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,…\n$ gear <dbl> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3,…\n$ carb <dbl> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, 1, 1, 2,…\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mpg             cyl             disp             hp       \n Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  \n 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  \n Median :19.20   Median :6.000   Median :196.3   Median :123.0  \n Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  \n 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  \n Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  \n      drat             wt             qsec             vs        \n Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  \n 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  \n Median :3.695   Median :3.325   Median :17.71   Median :0.0000  \n Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  \n 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  \n Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  \n       am              gear            carb      \n Min.   :0.0000   Min.   :3.000   Min.   :1.000  \n 1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000  \n Median :0.0000   Median :4.000   Median :2.000  \n Mean   :0.4062   Mean   :3.688   Mean   :2.812  \n 3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000  \n Max.   :1.0000   Max.   :5.000   Max.   :8.000  \n```\n\n\n:::\n:::\n\n\n> *(a) 32 rows × 11 columns · (b) one row = one car model (the row names are\n> the cars) · (c) all numeric — every column is `dbl` · (d) none —\n> `summary()` shows no `NA's` line for any column · (e) median mpg = 19.2*\n\n::: {.callout-note title=\"Expected — YT1\"}\n- [YT1]{.yt} **(a)** 32 × 11\n- **(b)** one row = one car model — the row *names* are the cars (first time they've seen row names carry meaning)\n- **(c)** all numeric — `dbl` everywhere, even `cyl`, `am`, `gear`, which are really categories (connect to Monday's item E)\n- **(d)** none — `summary()` shows no NA row\n- **(e)** median mpg = **19.2**\n- Teaching note: the point of YT1 is that they choose the functions themselves — don't prescribe which\n:::\n\n{{< vspace 1.5rem >}}\n\n# 2 · Accessing data — just enough [18 min]{.timing}\n\nThree tools, three jobs. You need to *read* all three; you'll *write* mostly\nthe first one:\n\n| Tool | Job | Returns |\n|---|---|---|\n| `$` | one column, **by name** | a vector |\n| `[rows, cols]` | a rectangle, by position/name | usually a data frame |\n| `[[ ]]` | one element, dug out | the thing itself |\n\n**LM4 — `$`, the workhorse (4 min).**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM4: a column is a vector\nairquality$Temp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] 67 72 74 62 56 66 65 59 61 69 74 69 66 68 58 64 66 57 68 62 59 73 61 61 57\n [26] 58 57 67 81 79 76 78 74 67 84 85 79 82 87 90 87 93 92 82 80 79 77 72 65 73\n [51] 76 77 76 76 76 75 78 73 80 77 83 84 85 81 84 83 83 88 92 92 89 82 73 81 91\n [76] 80 81 82 84 87 85 74 81 82 86 85 82 86 88 86 83 81 81 81 82 86 85 87 89 90\n[101] 90 92 86 86 82 80 79 77 79 76 78 78 77 72 75 79 81 86 88 97 94 96 94 91 92\n[126] 93 93 87 84 80 78 75 73 81 76 77 71 71 78 67 76 68 82 64 71 81 69 63 70 77\n[151] 75 76 68\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(airquality$Temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 77.88235\n```\n\n\n:::\n:::\n\n\n> 👀 **Variables check.** Nothing new — we *looked* at a column but never\n> assigned it. Now run `july_temp <- airquality$Temp[airquality$Month == 7]`\n> in the Console: Variables shows it as a numeric vector of length 31.\n\n::: {.callout-note title=\"Expected\"}\n- **77.88°F**\n:::\n\n> *YT2 (5 min). ➕ Insert a chunk. Using `$`, find:*\n> *(a) the mean of Wind;*\n> *(b) the max Temp;*\n> *(c) the mean of Ozone — it comes back `NA`. Fix it with the argument you\n> looked up in the help page last week;*\n> *(d) how many days had Temp above 90? (Hint: `sum(airquality$Temp > 90)` —\n> TRUE counts as 1.)*\n\n<!-- ➕ insert a chunk here -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT2\nmean(airquality$Wind)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.957516\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(airquality$Temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(airquality$Ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(airquality$Ozone, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 42.12931\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(airquality$Temp > 90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n:::\n\n\n> *(a) 9.96 mph · (b) 97 · (c) `NA`, then 42.13 with `na.rm = TRUE` ·\n> (d) 14 days*\n\n::: {.callout-note title=\"Expected — YT2\"}\n- [YT2]{.yt} **(a)** 9.96 mph\n- **(b)** 97\n- **(c)** `NA`, then **42.13** with `na.rm = TRUE` — the callback to Foundations 01 Q5; let someone remember it before you say it\n- **(d)** **14 days** — the first *logical vector doing arithmetic* (TRUE = 1); say it once, it returns with `filter()` Monday\n:::\n\n**LM5 — `[rows, columns]` and `[[ ]]`, in one pass (4 min).** Predict each\nbefore running. Square brackets take a *position or a name*; double brackets\ndig out *one thing*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM5: predict, then run\nairquality[1, ]                        # first row, all columns\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Ozone\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Solar.R\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Wind\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Temp\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Month\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Day\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"41\",\"2\":\"190\",\"3\":\"7.4\",\"4\":\"67\",\"5\":\"5\",\"6\":\"1\",\"_rn_\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nairquality[1:5, c(\"Ozone\", \"Temp\")]    # a rectangle\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Ozone\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Temp\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"41\",\"2\":\"67\",\"_rn_\":\"1\"},{\"1\":\"36\",\"2\":\"72\",\"_rn_\":\"2\"},{\"1\":\"12\",\"2\":\"74\",\"_rn_\":\"3\"},{\"1\":\"18\",\"2\":\"62\",\"_rn_\":\"4\"},{\"1\":\"NA\",\"2\":\"56\",\"_rn_\":\"5\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nairquality[[1, \"Temp\"]]                # one cell, dug out\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67\n```\n\n\n:::\n\n```{.r .cell-code}\n# the same three tools on a list (Monday's junk drawer):\nmy_list <- list(nums = c(1, 2, 3), word = \"hello\")\nmy_list$word\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"hello\"\n```\n\n\n:::\n\n```{.r .cell-code}\nmy_list[[\"nums\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 2 3\n```\n\n\n:::\n:::\n\n\n> *Q4. `airquality$Temp` and `airquality[[\"Temp\"]]` give the same vector.\n> `airquality[\"Temp\"]` does not — what is it instead? A one-column data\n> frame (the printed column header gives it away).*\n\n::: {.callout-tip title=\"Q4 answer — rule of thumb, and stop there\"}\n- [Q4]{.q} `airquality[\"Temp\"]` is still a **data frame** (one column); `$` and `[[ ]]` return the bare vector\n- Rule of thumb to leave them with, and *no more than this today*:\n  - `$` → a column you'll compute on (90% of what you'll write)\n  - `[rows, cols]` → a rectangle (you'll read it in other people's code; Monday `filter()`/`select()` replace it)\n  - `[[ ]]` → dig one thing out of a container (lists, week 8)\n- Deeper indexing rules are drill material, not lecture material\n:::\n\n> *YT3 (5 min). ➕ Insert a chunk. Switch to `iris`. Write ONE line for each:*\n> *(a) the Species column as a vector — how long is it?*\n> *(b) rows 51–53, all columns — what species are they?*\n> *(c) the last row of iris (use `nrow()` inside the brackets — no\n> hard-coded 150).*\n\n<!-- ➕ insert a chunk here -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT3\nlength(iris$Species)          # (a) 150\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150\n```\n\n\n:::\n\n```{.r .cell-code}\niris[51:53, ]                 # (b) versicolor\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sepal.Length\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sepal.Width\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Petal.Length\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Petal.Width\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Species\"],\"name\":[5],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"7.0\",\"2\":\"3.2\",\"3\":\"4.7\",\"4\":\"1.4\",\"5\":\"versicolor\",\"_rn_\":\"51\"},{\"1\":\"6.4\",\"2\":\"3.2\",\"3\":\"4.5\",\"4\":\"1.5\",\"5\":\"versicolor\",\"_rn_\":\"52\"},{\"1\":\"6.9\",\"2\":\"3.1\",\"3\":\"4.9\",\"4\":\"1.5\",\"5\":\"versicolor\",\"_rn_\":\"53\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\niris[nrow(iris), ]            # (c) row 150 — virginica\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sepal.Length\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sepal.Width\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Petal.Length\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Petal.Width\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Species\"],\"name\":[5],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"5.9\",\"2\":\"3\",\"3\":\"5.1\",\"4\":\"1.8\",\"5\":\"virginica\",\"_rn_\":\"150\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n::: {.callout-tip title=\"YT3 notes\"}\n- [YT3]{.yt} **(a)** 150 · **(b)** versicolor · **(c)** row 150, virginica\n- **(c)** is the one to check: `nrow()` *inside* the bracket — ask \"what if tomorrow the file has 200 rows?\" — that's why we don't type 150\n:::\n\n{{< vspace 1.5rem >}}\n\n# 3 · The pipe `|>` — the symbol you'll type more than any other [15 min]{.timing}\n\n::: {.callout-important title=\"Read this one out loud\"}\n**`|>` means \"and then.\"** Take the thing on the left, hand it to the function\non the right. That's it. Everything from Monday on — every ETV cycle, every\nplot, every summary — is a chain of *and then*s.\n:::\n\n**LM6 — the same code, two ways (5 min).** Question: *on average, how warm\nwere the July days?* Without the pipe, you read this **inside-out**, from the\ndeepest parentheses to the outermost:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM6a: nested — read from the INSIDE out\nround(mean(airquality$Temp[airquality$Month == 7]), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 83.9\n```\n\n\n:::\n:::\n\n\nWith the pipe, you read it **top-to-bottom, like a recipe**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM6b: piped — read \"and then\", top to bottom\nairquality$Temp[airquality$Month == 7] |>\n  mean() |>\n  round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 83.9\n```\n\n\n:::\n:::\n\n\nSame answer, 83.9°F. But the second one you can *say*: \"take July's\ntemperatures, **and then** average them, **and then** round to one decimal.\"\n\n::: {.callout-note title=\"How the pipe works — the one rule\"}\n- `x |> f()` is exactly `f(x)`. The left side becomes the **first argument** of the function on the right\n- `x |> f(y)` is `f(x, y)` — extra arguments go where they always did\n- So `airquality$Temp |> mean(na.rm = TRUE)` is `mean(airquality$Temp, na.rm = TRUE)`\n- Keyboard: **Cmd/Ctrl + Shift + M** types `|>` for you in Positron (if it types `%>%`, that's the older tidyverse pipe — same idea; set the *native pipe* option in Positron's settings)\n- Style: one step per line, indent the continuation. Your eye follows the recipe\n:::\n\n**LM7 — a real chain (4 min).** Which days are missing Ozone? Read each\nline as \"and then\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM7: WHICH rows are missing Ozone? — read it as a sentence\nairquality$Ozone |>\n  is.na() |>\n  which() |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  5 10 25 26 27 32\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Expected — LM7\"}\n- **rows 5, 10, 25, 26, 27, 32**\n- Have a student read the chain aloud: \"take Ozone, and then flag the NAs, and then find their positions, and then show the first six.\" If they can say it, they can write it\n- The nested version is `head(which(is.na(airquality$Ozone)))` — put it on the projector next to the pipe. Nobody prefers the nested one\n:::\n\n> *YT4 (6 min). ➕ Insert a chunk. Rewrite each nested line as a pipe, one\n> step per line, and confirm the answer doesn't change:*\n> *(a) `sqrt(mean(airquality$Wind))`*\n> *(b) `round(mean(airquality$Ozone, na.rm = TRUE), 2)`*\n> *(c) `length(unique(iris$Species))`*\n> *Then write ONE pipe of your own: three steps, any data, and a comment\n> reading it as a sentence.*\n\n<!-- ➕ insert a chunk here -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4\nairquality$Wind |> mean() |> sqrt()                    # (a) 3.156\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.155553\n```\n\n\n:::\n\n```{.r .cell-code}\nairquality$Ozone |> mean(na.rm = TRUE) |> round(2)     # (b) 42.13\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 42.13\n```\n\n\n:::\n\n```{.r .cell-code}\niris$Species |> unique() |> length()                   # (c) 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\n# my own: \"take Temp, and then keep the values above 90, and then count them\"\nairquality$Temp[airquality$Temp > 90] |> length()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"YT4 notes\"}\n- [YT4]{.yt} **(a)** 3.156 · **(b)** 42.13 · **(c)** 3\n- **(b)** is the check: `na.rm = TRUE` stays *inside* `mean()` — the pipe only fills the first argument\n- The \"own pipe\" is the deliverable: walk the room, ask three students to read theirs aloud. Monday's `coffee |> filter(...) |> ggplot(...)` is the same grammar with better verbs\n:::\n\n{{< vspace 1.5rem >}}\n\n# 3b · When things break [5 min]{.timing}\n\nToday's errors are *access* errors — asking for something that isn't where\nyou pointed. Read, name the family, fix.\n\n> *YT4b (5 min). Each chunk below has ONE bug. Read the error (or the\n> silent `NULL`!), fix it in place, and write the error family in the comment.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4b-1 — error family: ____\nmean(airquality$temp)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4b-1 — error family: column-name typo — `$` on a missing column returns NULL, mean() warns and gives NA (R is case-sensitive)\nmean(airquality$Temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 77.88235\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4b-2 — error family: ____\nairquality[1:5, c(\"Ozone\", \"Temperature\")]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4b-2 — error family: undefined columns selected — the name in [ ] must match exactly\nairquality[1:5, c(\"Ozone\", \"Temp\")]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Ozone\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Temp\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"41\",\"2\":\"67\",\"_rn_\":\"1\"},{\"1\":\"36\",\"2\":\"72\",\"_rn_\":\"2\"},{\"1\":\"12\",\"2\":\"74\",\"_rn_\":\"3\"},{\"1\":\"18\",\"2\":\"62\",\"_rn_\":\"4\"},{\"1\":\"NA\",\"2\":\"56\",\"_rn_\":\"5\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4b-3 — error family: ____\nairquality$Ozone |>\n  is.na() |>\n  which()\n  head()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT4b-3 — error family: a broken pipe — the missing |> means head() runs on nothing (error: argument \"x\" is missing)\nairquality$Ozone |>\n  is.na() |>\n  which() |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  5 10 25 26 27 32\n```\n\n\n:::\n:::\n\n\n::: {.callout-caution title=\"YT4b answers — three error families for accessing data\"}\n- [YT4b-1]{.yt} `airquality$temp` → `NULL`, then `mean()` warns and returns `NA` — **no red error**\n  - family: **column-name typo with `$`** (case-sensitive) — the sneakiest, same as Fnd 01 YT7a\n  - fix: `Temp`; habit: `names(airquality)` first\n- [YT4b-2]{.yt} `Error in [.data.frame: undefined columns selected`\n  - family: **wrong name inside `[ ]`** — brackets *do* error where `$` stays silent\n  - fix: `\"Temp\"`\n- [YT4b-3]{.yt} `Error in head(): argument \"x\" is missing, with no default`\n  - family: **broken pipe** — a line without `|>` at its end ends the chain; the next line runs alone\n  - fix: add the `|>`; rule: every line of a chain except the last ends in `|>`\n- Land the contrast: `$` fails *quietly*, `[ ]` fails *loudly*, a pipe fails *one line late*. Reading the message tells you which\n:::\n\n{{< vspace 1.5rem >}}\n\n# 4 · How big is data? [11 min]{.timing}\n\n**LM8 — the ladder (4 min).** Data size is measured in **bytes** — one byte\nis roughly one letter. Every step up the ladder multiplies by a thousand:\n\n![Each step is ×1,000. A byte is a letter; a kilobyte is a paragraph; a megabyte is a photo; a gigabyte is an hour of video; a terabyte is a whole laptop.](/assets/byte_ladder.svg){fig-alt=\"Ladder of storage units from byte to terabyte, each step ×1,000, with an everyday example on each step.\" width=\"100%\"}\n\n**LM9 — where real things land (4 min).** The bars below are on a *log*\nscale — each gridline is another ×1,000. Notice where **your laptop's\nmemory** sits, because that's the ceiling for what R can hold:\n\n![Real-world sizes on a log scale, from one letter to a national census. The orange \"laptop memory\" bar is the amount of data R can hold at once.](/assets/how_big_is_it.svg){fig-alt=\"Horizontal bar chart on a log scale showing sizes of everyday things: a text message (bytes), a survey CSV (KB), a song (MB), an hour of HD video (GB), a laptop's RAM (8–16 GB), a laptop drive (512 GB), and a census extract (1 TB).\" width=\"100%\"}\n\n| Unit | ≈ bytes | Something you own that's about that size |\n|---|---|---|\n| **byte** | 1 | one letter of a text message |\n| **kilobyte (KB)** | 1 thousand | a long email; this class's survey as a `.csv`; `airquality` (5.6 KB) |\n| **megabyte (MB)** | 1 million | one phone photo (3 MB); one song (4 MB); a year of CA crime data (~100 MB) |\n| **gigabyte (GB)** | 1 billion | an hour of HD Netflix (3 GB); your laptop's **memory** (8–16 GB) |\n| **terabyte (TB)** | 1 trillion | two of your laptop's drives; a full US census extract |\n| **petabyte (PB)** | 1 quadrillion | Netflix's entire catalog; the data behind a weather forecast |\n\nNow measure **our** objects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LM9: how big are OUR objects?\nobject.size(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n5632 bytes\n```\n\n\n:::\n\n```{.r .cell-code}\nobject.size(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n7256 bytes\n```\n\n\n:::\n\n```{.r .cell-code}\nobject.size(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n7208 bytes\n```\n\n\n:::\n:::\n\n\n> *Q5. Order the three from smallest to largest, and name the unit they're\n> in: airquality (≈ 5.6 KB) < mtcars (≈ 7.2 KB) < iris (≈ 7.3 KB) — all\n> kilobytes, i.e. a few paragraphs each.*\n\n**Why it matters (3 min):** R holds data **in memory** — the orange bar, not\nthe red one. A 2 GB file on an 8 GB laptop imports (barely); a 200 GB file\ndoes not — you'd need different tools (a database, or a bigger machine). File\nsize is the first thing to check *before* importing, which is exactly where\nnext week begins.\n\n> *Q6. Your laptop has 8 GB of memory. Roughly how many copies of a 500 MB\n> dataset could fit at once (ignore overhead)? About 16 — 8 GB ≈ 8,000 MB,\n> and 8,000 / 500 = 16. How many hours of HD video is that? Not even three.*\n\n::: {.callout-tip title=\"Q5 & Q6 answers\"}\n- [Q5]{.q} actually run it: airquality ≈ 5.6 KB, mtcars ≈ 7.2 KB, iris ≈ 7.3 KB → **airquality < mtcars < iris**, all in KB\n  - mtcars is small in rows but its row *names* cost bytes — a fun 20-second aside if asked; otherwise just confirm the order\n- [Q6]{.q} **about 16 copies** — 8 GB ≈ 8,000 MB; 8,000 / 500 = 16; that whole 8 GB is under three hours of HD video\n  - honest version: overhead means fewer in practice; R also copies objects when you modify them\n  - the point is *order-of-magnitude* reasoning, which is sub-outcome 1.12's whole job\n- Land the contrast: their **phone camera roll** (tens of GB) is bigger than any dataset they'll open in this course — data science files are not the big files in their life\n:::\n\n> *YT5 (2 min). ➕ Insert a chunk. Run `object.size(iris)` and then\n> `object.size(iris$Sepal.Length)`. Roughly what fraction of the whole is\n> one column? Does that match \"1 of 5 columns\"? One sentence on why or why\n> not.*\n\n<!-- ➕ insert a chunk here -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# YT5\nobject.size(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n7256 bytes\n```\n\n\n:::\n\n```{.r .cell-code}\nobject.size(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1248 bytes\n```\n\n\n:::\n:::\n\n\n> *One column is ≈ 1.2 KB of ≈ 7.3 KB — about 17%, which is less than 1/5.\n> It doesn't match because the data frame itself costs something: column\n> names, row labels, and the Species factor's level table are stored on top\n> of the raw numbers.*\n\n::: {.callout-tip title=\"YT5 answer\"}\n- [YT5]{.yt} one column ≈ 1.2 KB of ≈ 7.3 KB — about **17%**, less than 1/5\n- Why: the data frame carries overhead (names, row labels, the factor's level table) beyond its raw numbers\n- Full credit: any answer noticing \"less than 1/5, because the container itself costs something\"\n:::\n\n{{< vspace 1.5rem >}}\n\n# 5 · Where this is going [5 min — watch]{.timing}\n\nInstructor runs one **complete ETV cycle live**, start to finish, no pauses:\nimport a CSV → transform → plot. Every function you just learned appears in\nthe first thirty seconds — and every line is joined by `|>`. Monday, you\ndrive.\n\n::: {.callout-important title=\"Teaching note — the ETV preview\"}\n- Run the coffee import → `filter` → histogram in under three minutes\n- Say only: *\"Extraction. Transformation. Visualization. Monday, this is yours.\"* — and point at each `|>` as you go: \"and then\"\n- No function explanations — the mystique is the motivation\n:::\n\n# 6 · Exit question [4 min]{.timing}\n\n> *You're handed `mysterydata`, a data frame you've never seen. Write the\n> three lines you'd run FIRST, in order, and say what each tells you. Then\n> write ONE pipe that takes the column `score`, removes NAs from its mean,\n> and rounds to one decimal.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your three inspection lines:\nglimpse(mysterydata)      # structure: rows, columns, names, types\nsummary(mysterydata)      # ranges + WHERE the NAs are\nhead(mysterydata)         # what the values actually look like\n\n# your one pipe:\nmysterydata$score |>\n  mean(na.rm = TRUE) |>\n  round(1)\n```\n:::\n\n\n> *Your explanation:* `glimpse()` first tells me the shape (rows, columns),\n> the names, and the type of every column. `summary()` then gives the range\n> of each numeric column and, crucially, where the `NA`s are. `head()` shows\n> what the values actually look like so I can sanity-check the types. Then\n> the pipe reads \"take score, and then average it ignoring NAs, and then\n> round to one decimal.\"\n\n::: {.callout-tip title=\"Model answer\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mysterydata)      # structure: rows, columns, names, types\nsummary(mysterydata)      # ranges + WHERE the NAs are\nhead(mysterydata)         # what the values actually look like\n\nmysterydata$score |> mean(na.rm = TRUE) |> round(1)\n```\n:::\n\n\n- Passes: any three of {`glimpse`/`str`, `summary`, `head`/`tail`, `dim`/`nrow`+`ncol`, `names`} with correct one-line justifications\n- The pipe must start from `mysterydata$score` (or `[[\"score\"]]`) and keep `na.rm = TRUE` *inside* `mean()`; `mysterydata[\"score\"]` is a data frame — half credit with the explanation\n- The habits being graded: **inspect before you compute**, and **write it as a recipe**\n:::\n\n# 7 · Save & render [1 min]{.timing}\n\nSave this file into your `R/Notes/` folder as `fnd03_yourlastname.qmd`. Then\n**Restart R** — watch Variables empty out — and press **Render**. That is\nthe last foundations document; from Monday every file you render is an ETV\ncycle, and every one of them starts with the three inspection lines from\ntoday's exit question.\n",
    "supporting": [
      "fnd03_inspect_access_solution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}